# Ted Bunton
## Week 11 11/05/2020
### Python NumPy Universal Functions

In [2]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]

z = []

for i, j in zip(arr1,arr2):
    z.append(i+j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [3]:
#zip

fname = ("Alice", "Bob", "Christy")
lname = ("Charlie", "Clark", "Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [4]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [5]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
arr1 = np.random.randn(10)

arr1

array([ 0.94187208,  1.53022135, -0.49377804,  1.73745318, -0.39860965,
        0.14430184, -0.64162181,  0.84688328, -0.30451799,  0.60649043])

In [10]:
arr2 = np.random.randn(10)

arr2

array([-0.23980167, -0.64118188, -2.25729382, -0.96013323,  0.16557908,
       -0.73570809, -0.98377314,  1.15002914, -1.66804197, -0.61348958])

In [11]:
np.add(arr1,arr2)

array([ 0.70207041,  0.88903947, -2.75107187,  0.77731995, -0.23303057,
       -0.59140626, -1.62539496,  1.99691242, -1.97255997, -0.00699915])

In [12]:
np.maximum(arr1,arr2)

array([ 0.94187208,  1.53022135, -0.49377804,  1.73745318,  0.16557908,
        0.14430184, -0.64162181,  1.15002914, -0.30451799,  0.60649043])

In [13]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [15]:
np.where(arr < 4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
np.where((arr < 4) & (arr > 2), -1, -2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [17]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [18]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [19]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [20]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True,False],[True,True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [22]:
np.where([[True,False],[True,True]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [25]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[-0.53723326,  0.96010242, -1.26616224],
       [-0.60095504,  0.90935813, -0.11565452],
       [ 0.99549843,  1.75910412,  0.18153069]])

In [24]:
np.where(arr<0, 0,arr)

array([[0.        , 0.46426519, 0.35168289, 0.        , 1.55298731],
       [1.7890456 , 0.71560466, 1.64112577, 0.        , 0.97743029],
       [0.        , 0.82493279, 0.        , 0.        , 0.        ],
       [0.91267675, 1.5373377 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.11173918, 0.        , 0.1953662 ]])

In [26]:
arr_b = np.array([True,False,True,False])

arr_b.any()

True

In [27]:
arr_b.all()

False

In [28]:
fruits = np.array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [29]:
np.in1d(['Apple', 'Cherry', 'Grape'],fruits)

array([ True,  True, False])

In [30]:
#Statistical measures

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
arr.sum()

45

In [32]:
arr.sum(0)

array([12, 15, 18])

In [33]:
arr.sum(1)

array([ 6, 15, 24])

In [34]:
arr.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [35]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [36]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [37]:
print(arr)
np.sum(arr, axis=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [38]:
arr.mean()

5.0

In [39]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [40]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [42]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [43]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [44]:
arr.var()

6.666666666666667

In [45]:
arr.std()

2.581988897471611

In [46]:
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])

arr.sort()

arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [47]:
#identity array
i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
a = np.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [51]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)

a * i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [52]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [53]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [54]:
#Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)
print(arr)
print('----------------')

t = arr.T

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
----------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [55]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [56]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [58]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [59]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [60]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [61]:
arr_3d.transpose((1,0,3))

AxisError: axis 3 is out of bounds for array of dimension 3

In [62]:
np.random.random((4,4))

array([[0.1307921 , 0.17393542, 0.54091424, 0.62874399],
       [0.43583239, 0.0531623 , 0.84180932, 0.90765569],
       [0.41208254, 0.48382425, 0.62617128, 0.50882128],
       [0.6784301 , 0.16907914, 0.98341319, 0.2441256 ]])

In [63]:
from numpy.random import random
random((4,4))

array([[0.18221108, 0.63678352, 0.49320127, 0.11033237],
       [0.85209738, 0.15174982, 0.74466779, 0.31737212],
       [0.86084703, 0.23804044, 0.07373874, 0.19357939],
       [0.35474503, 0.24693906, 0.45508754, 0.72930546]])

In [64]:
from numpy.random import randn
randn(5,5)

array([[ 1.54642355,  0.1289231 , -0.59653414, -0.3662933 ,  1.34194916],
       [ 0.02440762, -1.01628179,  1.34129747, -1.40542287,  1.20252493],
       [-1.05997874,  0.51835467,  1.74951562,  1.67389073,  0.07604987],
       [-0.19967873, -0.63645201,  0.68798212,  0.07623665, -0.63143253],
       [ 0.20772642, -0.72411814, -0.24019983,  0.64305007,  0.98889412]])

In [65]:
randn(5)

array([ 0.20622757, -1.73741677, -1.54722328, -0.9103925 ,  0.33367934])

In [66]:
np.random.randint(10,50)

10

In [67]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

import webbrowser
webbrowser.open(website)

True

In [68]:
import pandas as pd