# Ted Bunton
## Week 11 11/03/2020
### Python numpy creating, processing, transporting arrays

In [1]:
import numpy as np

arr_2d = np.array([[1,2,3,4],[5,6,7,8]])

print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print(arr.ndim)
print(arr.dtype)

1
float64
